'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'brand.name.full': 'Astro Suvid',
    'brand.name.prefix': 'Astro',
    'brand.name.highlight': 'Suvid',
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.blog': 'Blog',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.consult': 'Consult Now',
    'nav.expert': 'Expert Consultation',

    // Hero
    'hero.relationship.title': 'Love Life &',
    'hero.relationship.title.highlight': 'Marriage Success',
    'hero.relationship.subtitle': 'Get clarity on your love life and marriage through ancient wisdom.',
    'hero.career.title': 'Stuck in career &',
    'hero.career.title.highlight': 'Want growth?',
    'hero.career.subtitle': 'Unlock your best career growth and success through astrology.',
    'hero.health.title': 'Grow in your',
    'hero.health.title.highlight': 'Health & Mental Health',
    'hero.health.subtitle': 'Improve your health and get mental peace through ancient wisdom.',
    'hero.vastu.title': 'Vastu Shastra &',
    'hero.vastu.title.highlight': 'Home Peace',
    'hero.vastu.subtitle': 'Make your home a place of peace and prosperity with Vastu.',
    'hero.business.title': 'Business &',
    'hero.business.title.highlight': 'Money Growth',
    'hero.business.subtitle': 'Grow your business and increase your wealth with astrology.',
    'hero.matchmaking.title': 'Kundli Matching &',
    'hero.matchmaking.title.highlight': 'Happy Marriage',
    'hero.matchmaking.subtitle': 'Ensure a happy married life with deep kundli matching.',
    'hero.matrimonial.title': 'Find Your',
    'hero.matrimonial.title.highlight': 'Life Partner',
    'hero.matrimonial.subtitle': 'Find the best life partner based on your values and stars.',
    'hero.cta.book': 'Book Consultation',
    'hero.cta.services': 'Explore Services',
    'hero.cta.relationship': 'Love Consultation',
    'hero.cta.career': 'Career Guidance',
    'hero.cta.health': 'Health Consultation',
    'hero.cta.vastu': 'Vastu Consultation',
    'hero.cta.business': 'Business Astrology',
    'hero.cta.matchmaking': 'Check Compatibility',
    'hero.cta.matrimonial': 'Register for Matrimony',
    'hero.call': 'Call',
    'hero.chat': 'WhatsApp',

    // Services
    'services.title': 'Our',
    'services.title.highlight': 'Services',
    'services.subtitle': "We combine traditional knowledge with practical advice to help you make better life decisions.",
    'services.sacred': 'Special Astrology Services',
    'services.sacred.subtitle': 'Expert Vedic astrology and Tarot readings to guide you in your life journey',
    'services.includes': 'Includes:',
    'services.duration': 'Duration:',
    'services.ready': 'Ready to solve your problems?',
    'services.ready.subtitle': 'Choose the service you need and get expert guidance today.',
    'services.book': 'Book Your Session',
    'services.explore_all': 'Explore All',
    'services.begin_journey': 'Begin Your Journey',
    'services.our_services': 'Our Services',

    // Service 1: Birth Chart Analysis
    'service.birth.title': 'Birth Chart Analysis',
    'service.birth.desc': 'Deep analysis of your natal chart to understand your personality, strengths, and life path.',
    'service.birth.f1': 'Planetary positions at birth',
    'service.birth.f2': 'House analysis and meanings',
    'service.birth.f3': 'Zodiac sign interpretations',
    'service.birth.f4': 'Aspect analysis for relationships',
    'service.birth.f5': 'Dasha predictions',
    'service.birth.duration': '60 minutes',

    // Service 2: Planetary Predictions
    'service.planetary.title': 'Planetary Predictions',
    'service.planetary.desc': 'Get insights into upcoming planetary transits and their influence on your life.',
    'service.planetary.f1': 'Current planetary movements',
    'service.planetary.f2': 'Upcoming opportunities',
    'service.planetary.f3': 'Challenges and solutions',
    'service.planetary.f4': 'Timing for important decisions',
    'service.planetary.f5': 'Remedial measures (Upayes)',
    'service.planetary.duration': '45 minutes',

    // Service 3: Career Guidance
    'service.career.title': 'Career Guidance',
    'service.career.desc': 'Vedic insights to help you find your ideal career path and professional growth.',
    'service.career.f1': '10th house analysis',
    'service.career.f2': 'Career compatibility',
    'service.career.f3': 'Best time for career changes',
    'service.career.f4': 'Business opportunities',
    'service.career.f5': 'Success indicators',
    'service.career.duration': '50 minutes',

    // Service 4: Relationship Insights
    'service.relationship.title': 'Relationship Insights',
    'service.relationship.desc': 'Understand your relationship patterns and compatibility with your partner.',
    'service.relationship.f1': 'Synastry analysis',
    'service.relationship.f2': 'Compatibility report',
    'service.relationship.f3': 'Timing for commitments',
    'service.relationship.f4': 'Family harmony insights',
    'service.relationship.f5': 'Guidance for challenges',
    'service.relationship.duration': '60 minutes',

    // Service 5: Tarot Card Reading
    'service.tarot.title.main': 'Tarot Card Reading',
    'service.tarot.desc.main': 'Intuitive guidance through tarot to illuminate your current situation and future path.',
    'service.tarot.main.f1': 'Three-card spread',
    'service.tarot.main.f2': 'Detailed card interpretations',
    'service.tarot.main.f3': 'Life advice and guidance',
    'service.tarot.main.f4': 'Energy clearing insights',
    'service.tarot.main.f5': 'Spiritual messages',
    'service.tarot.main.duration': '45 minutes',

    // Service 6: Life Purpose Session
    'service.purpose.title': 'Life Purpose Session',
    'service.purpose.desc': "Discover your soul's purpose and life mission through vedic wisdom.",
    'service.purpose.f1': 'Nodal axis analysis',
    'service.purpose.f2': 'Soul karmic lessons',
    'service.purpose.f3': 'Life purpose indicators',
    'service.purpose.f4': 'Spiritual growth path',
    'service.purpose.f5': 'Fulfillment strategies',
    'service.purpose.duration': '75 minutes',

    // Service 1: Vedic Astrology
    'service.vedic.title': 'Vedic Astrology',
    'service.vedic.desc': 'Get detailed life predictions based on your birth chart and planetary positions.',
    'service.vedic.f1': 'Birth Chart Analysis',
    'service.vedic.f2': 'Planetary Dashas',
    'service.vedic.f3': 'Career & Wealth',
    'service.vedic.f4': 'Relationship Compatibility',

    // Service 2: Tarot Reading
    'service.tarot.title': 'Tarot Reading',
    'service.tarot.desc': 'Simple and effective guidance to understand your current situation and future possibilities.',
    'service.tarot.f1': 'Intuitive Spreads',
    'service.tarot.f2': 'Spiritual Growth',
    'service.tarot.f3': 'Decision Clarity',
    'service.tarot.f4': 'Energy Alignment',

    // New Services Section
    'service.kundli.title': 'Janm Kundli Reading',
    'service.kundli.desc': '(Understand your life, career, marriage & future deeply) through vedic astrology',
    'service.kundli.btn': 'Ask Now',
    'service.kundli.details': 'Deep analysis of your natal chart including planetary positions at birth, house analysis, zodiac sign interpretations, and dasha predictions for all life aspects.',
    
    'service.prashna.title': 'Prashna Kundli',
    'service.prashna.desc': 'Get answers to your specific questions instantly',
    'service.prashna.btn': 'Ask Now',
    'service.prashna.details': 'Horary astrology providing immediate answers to specific queries without a birth chart, based on the planetary alignment at the moment of asking.',
    
    'service.tarot.title': 'Tarot Reading',
    'service.tarot.desc': 'Intuitive guidance through tarot to illuminate your current situation and future path',
    'service.tarot.btn': 'Book Now',
    'service.tarot.details': 'Expert tarot card reading to give you clarity on your relationships, career, and personal life.',
    
    'service.vastu.title': 'Vastu Consultation',
    'service.vastu.desc': 'Home / Shop / Office solutions',
    'service.vastu.btn': 'Book Visit',
    'service.vastu.details': 'Traditional Vastu tips for your home or office to bring more positivity, wealth, and peace in your life.',
    
    'service.gemstone.title': 'Gemstone Consultation & Purchase',
    'service.gemstone.desc': 'Get correct gemstone with certification',
    'service.gemstone.btn': 'View Stones',
    'service.gemstone.details': 'Get suggestions for high-quality, lab-certified gemstones based on your stars to help you succeed in life.',
    
    'service.matchmaking.title': 'Matchmaking Analysis',
    'service.matchmaking.desc': 'Deep compatibility check for successful marriage',
    'service.matchmaking.btn': 'Check Compatibility',
    'service.matchmaking.details': 'Detailed Kundli matching (Guna Milan) and check for Manglik Dosha to ensure a happy and long marriage.',
    
    'service.matrimonial.title': 'Matrimonial Services',
    'service.matrimonial.desc': 'Just Fill our matrimonial form and get your suitable partner',
    'service.matrimonial.btn': 'Fill Form',
    'service.matrimonial.details': 'A unique platform to find your life partner based on family values and kundli matching.',
    
    'service.business.title': 'Business Growth',
    'service.business.desc': 'Get astrological guidance for business success and loss recovery',
    'service.business.btn': 'Grow Business',
    'service.business.details': 'Strategic astrological consulting for entrepreneurs, focusing on auspicious launch timings, partnership compatibility, and financial recovery.',

    // Business Growth Page
    'business.hero.title': 'BUSINESS GROWTH PAGE',
    'business.hero.subtitle': 'Grow Your Business with Astrology Guidance',
    'business.hero.desc': 'If your business is stuck or facing losses, this service is for you -',
    'business.analyze.title': 'What we analyze:',
    'business.analyze.point1.title': 'Business Kundli',
    'business.analyze.point1.sub': '(Owner + Business start time)',
    'business.analyze.point1.desc': 'Comprehensive analysis of owner\'s chart combined with the business inception time.',
    'business.analyze.point2.title': 'Current Dasha & Planetary impact',
    'business.analyze.point2.desc': 'Understanding how current planetary periods are affecting your business operations.',
    'business.analyze.point3.title': 'Right Muhurta',
    'business.analyze.point3.sub': '(For Expansion / Starting new work)',
    'business.analyze.point3.desc': 'Finding the most auspicious timing for expansion or starting new ventures.',
    'business.analyze.point4.title': 'Partnership compatibility analysis',
    'business.analyze.point4.desc': 'Detailed analysis of business partners to ensure long-term harmony and success.',
    'business.analyze.point5.title': 'Financial blockage reasons',
    'business.analyze.point5.desc': 'Identifying astrological and practical reasons behind financial stagnation.',
    'business.solutions.title': 'Our Solutions',
    'business.solutions.subtitle': 'Practical and astrological remedies tailored for your business success.',
    'business.solutions.point1.title': 'Loss recovery remedies',
    'business.solutions.point1.desc': 'Specific astrological remedies to recover from business losses and stabilize finances.',
    'business.solutions.point2.title': 'Decision guidance at the right time',
    'business.solutions.point2.desc': 'Timing-based guidance to help you make the right business decisions at the right time.',
    'business.solutions.point3.title': 'Growth boosting remedies',
    'business.solutions.point3.sub': '(practical + astrological)',
    'business.solutions.point3.desc': 'A blend of practical business advice and astrological remedies to accelerate growth.',
    'business.solutions.point4.title': 'Business name / branding suggestions',
    'business.solutions.point4.desc': 'Numerological and astrological suggestions for business names and branding.',
    'business.feature.badge': 'Special Feature',
    'business.feature.title': 'Case Study Based Approach',
    'business.feature.point': '👉 Real अनुभव के आधार पर practical solutions',
    'business.feature.desc': "We don't just provide generic advice. Our approach is rooted in real-world scenarios and proven results from diverse business cases.",
    'business.ideal.title': 'Ideal For',
    'business.ideal.point1': 'Shop owners',
    'business.ideal.point2': 'Startup founders',
    'business.ideal.point3': 'Freelancers',
    'business.ideal.point4': 'Partnership businesses',
    'business.cta.book': 'Book Business Analysis',
    'business.cta.whatsapp': 'Get Guidance on WhatsApp',
    'business.whatsapp.message': 'Hello, I am interested in Business Growth Consultation.',

    // Matrimonial Page
    'matrimonial.hero.badge': 'Sacred Unions',
    'matrimonial.hero.title': 'Find Your Perfect Life Partner',
    'matrimonial.hero.subtitle': '(Astrology-Based Matching)',
    'matrimonial.hero.description': 'This is not just a matrimonial site — it is an astrology-based filtered matching system.',
    'matrimonial.how.title': 'How it Works',
    'matrimonial.how.step1': 'Register your profile',
    'matrimonial.how.step2': 'Submit Kundli details',
    'matrimonial.how.step3': 'Get shortlisted matching profiles',
    'matrimonial.how.step4': 'Data shared only after your permission',
    'matrimonial.privacy.title': 'Privacy Assurance',
    'matrimonial.privacy.text1': 'Your data will NOT be shared without your permission',
    'matrimonial.privacy.text2': 'Secure & confidential system',
    'matrimonial.features.title': 'Special Features',
    'matrimonial.features.1': 'Astrology-based profile matching',
    'matrimonial.features.2': 'Verified profiles (manual check)',
    'matrimonial.features.3': 'Direct consultation before final decision',
    'matrimonial.features.4': 'Premium matchmaking assistance (paid option)',
    'matrimonial.cta.register': 'Register Now',
    'matrimonial.cta.help': 'Get Matchmaking Help',
    'matrimonial.form.title': 'Profile Registration',
    'matrimonial.form.name': 'Full Name',
    'matrimonial.form.dob': 'Date of Birth',
    'matrimonial.form.tob': 'Time of Birth',
    'matrimonial.form.pob': 'Place of Birth',
    'matrimonial.form.gender': 'Gender',
    'matrimonial.form.caste': 'Caste / Gotra',
    'matrimonial.form.height': 'Height',
    'matrimonial.form.weight': 'Weight',
    'matrimonial.form.education': 'Education',
    'matrimonial.form.profession': 'Profession',
    'matrimonial.form.location': 'Location',
    'matrimonial.form.photo': 'Photo Upload',
    'matrimonial.form.submit': 'Register Profile',

    // Astro Mall
    'mall.title': 'The',
    'mall.title.highlight': 'Astro',
    'mall.subtitle': 'Buy original gemstones and items, tested and checked for quality to help you in your life journey.',
    'mall.coming_soon': 'Coming Soon - Items',
    'mall.enquire': 'Enquire Now',
    'mall.authentic': 'Authentic',
    'mall.mall': 'Mall',

    // Footer
    'footer.description': 'Helping you in your life journey through the knowledge of Vedic Astrology and Tarot Reading. Your trusted guide for better life decisions.',
    'footer.address': 'Lucknow, Uttar Pradesh, India',
    'footer.navigation': 'Navigation',
    'footer.services': 'Services',
    'footer.guides': 'Expert Guides',
    'footer.connect': 'Connect',
    'footer.legal': 'Legal',
    'footer.rights': 'Astro Suvid. All Rights Reserved. Built in India 🇮🇳',
    'footer.crafted': '',
    'footer.made_with': '',
    'footer.by_team': '',

    // Links
    'link.home': 'Home',
    'link.services': 'Services',
    'link.contact': 'Contact',
    'link.horoscope': 'Daily Horoscope',
    'link.career': 'Career Astrology',
    'link.marriage': 'Marriage Astrology',
    'link.kundli': 'Kundli Matching',
    'link.vastu': 'Vastu Consultation',
    'link.numerology': 'Numerology Services',
    'link.gemstone': 'Gemstone Consultation',
    'link.business': 'Business Growth',
    'link.tarot': 'Tarot Reading',
    'link.guide1': 'Best Vedic Astrologer in Lucknow',
    'link.guide2': 'Best Tarot Readers in Lucknow',
    'link.guide3': 'Best Astrologers in Lucknow',
    'link.guide4': 'Best Astrologers Globally',
    'link.privacy': 'Privacy Policy',
    'link.terms': 'Terms & Conditions',
    'link.cancellation': 'Cancellation & Refund',
    'link.shipping': 'Shipping & Delivery',

    // Contact Form
    'contact.title': 'Send Your Query',
    'contact.subtitle': 'Share your concerns and let the cosmic energy guide your path',
    'contact.success': "Thank you! Your query has been received. We'll get back to you soon with cosmic blessings.",
    'contact.error.name': 'Please enter your name',
    'contact.error.email': 'Please enter a valid email',
    'contact.error.phone': 'Please enter a valid phone number',
    'contact.error.service': 'Please select a service',
    'contact.error.message': 'Please enter your message',
    'contact.label.name': 'Full Name *',
    'contact.placeholder.name': 'Your name',
    'contact.label.email': 'Email *',
    'contact.placeholder.email': 'your@email.com',
    'contact.label.phone': 'Phone Number *',
    'contact.placeholder.phone': '+91 98765 43210',
    'contact.label.service': 'Service *',
    'contact.placeholder.service': 'Select a service',
    'contact.service.vedic': 'Vedic Astrology Consultation',
    'contact.service.tarot': 'Tarot Card Reading',
    'contact.service.both': 'Both Services',
    'contact.service.other': 'Other Inquiry',
    'contact.label.message': 'Your Message *',
    'contact.placeholder.message': 'Tell us about your concerns, questions, or what guidance you seek...',
    'contact.button.sending': 'Sending...',
    'contact.button.send': 'Send Query',
    'contact.privacy': 'We respect your privacy. Your information will only be used to provide you with cosmic guidance.',

    // Testimonials
    'testimonials.title': 'Celestial',
    'testimonials.title.highlight': 'Blessings',
    'testimonials.subtitle': 'Voices of those whose paths have been illuminated by cosmic wisdom.',
    'testimonials.1.name': 'Priya Sharma',
    'testimonials.1.role': 'Business Owner',
    'testimonials.1.text': "Darshi's Vedic Astrology reading gave me the clarity I needed during a challenging career transition. The insights were remarkably accurate and transformative.",
    'testimonials.2.name': 'Anjali Verma',
    'testimonials.2.role': 'Healthcare Professional',
    'testimonials.2.text': "The tarot readings have been incredibly helpful in understanding my relationships and personal growth. Darshi's intuition is truly exceptional.",
    'testimonials.3.name': 'Neha Patel',
    'testimonials.3.role': 'Creative Professional',
    'testimonials.3.text': "The birth chart analysis provided me with a deeper understanding of my strengths and potential. I've never felt more aligned with my purpose.",

    // Astrologer Profile
    'profile.title': 'Meet',
    'profile.title.highlight': 'Darshi',
    'profile.description': "A dedicated Vedic Astrologer and Tarot Reader with over a decade of experience in guiding seekers through life's cosmic journey. Darshi combines ancient Vedic wisdom with intuitive spiritual guidance to provide transformative readings tailored to your unique path.",
    'profile.cred1.title': 'Vedic Specialist',
    'profile.cred1.desc': 'Expert in Sidereal calculations and planetary periods (Dashas).',
    'profile.cred2.title': 'Certified Master',
    'profile.cred2.desc': 'Deeply trained in classical tarot symbolism and intuitive spreads.',
    'profile.expertise.title': 'Core Expertise',
    'profile.expertise.1': 'Career Guidance',
    'profile.expertise.2': 'Relationship Insights',
    'profile.expertise.3': 'Life Purpose',
    'profile.expertise.4': 'Spiritual Growth',
    'profile.expertise.5': 'Energy Alignment',

    // CTA Banner
    'cta.title': 'Unlock the Secrets of Your',
    'cta.title.highlight': 'Kundli',
    'cta.subtitle': "Get expert guidance for career, marriage, and life's biggest questions. Connect with Lucknow's most trusted astrologers for a personalized consultation.",
    'cta.button.book': 'Book Consultation',
    'cta.button.whatsapp': 'WhatsApp',
    'cta.trusted': 'Trusted by 500+ seekers worldwide',
    'cta.chart.title': 'Your Chart',
    'cta.chart.subtitle': '12 Houses · 9 Grahas',
    'cta.response.label': 'Response within',
    'cta.response.value': '24 hrs',

    // Nav language
    'nav.language': 'Language',

    // PWA install
    'pwa.bar.title': 'Install Astro Suvid App',
    'pwa.bar.subtitle': 'Quick access to consultations & horoscope',
    'pwa.modal.title': 'Install our app for the best experience',
    'pwa.modal.subtitle': 'Get instant access to astrology services, bookings, and updates — right from your home screen.',
    'pwa.install': 'Install',
    'pwa.installNow': 'Install App Now',
    'pwa.installing': 'Installing…',
    'pwa.later': 'Maybe later',
    'pwa.dismiss': "Don't show again",
    'pwa.benefit1': 'One-tap access from your home screen',
    'pwa.benefit2': 'Faster loading & app-like experience',
    'pwa.benefit3': 'Easy booking for consultations & services',
    'pwa.ios.step1': 'Tap the Share button at the bottom of Safari',
    'pwa.ios.step2': 'Scroll and tap "Add to Home Screen"',
    'pwa.ios.step3': 'Tap Add — Astro Suvid will appear on your home screen',
    'pwa.android.fallback': 'Tap the menu (⋮) in your browser and select "Install app" or "Add to Home screen".',

    // Footer consult
    'footer.consult.title': 'Consult',
    'footer.consult.desc': 'Questions about career, marriage, health, or gemstones? Speak with our team directly.',
    'footer.whatsapp': 'WhatsApp',

    // Why Choose Us
    'why.title': 'Guidance that feels',
    'why.title.highlight': 'human',
    'why.title.suffix': ', not generated.',
    'why.subtitle': 'Ancient Jyotish logic, explained in plain language — with care, clarity, and remedies you can actually use.',
    'why.stat1.label': 'Years guiding seekers',
    'why.stat2.label': 'Consultations delivered',
    'why.stat3.label': 'Confidential sessions',
    'why.feature1.title': 'Qualified expert team',
    'why.feature1.desc': 'Readings led by trained Vedic astrologers — not automated software output.',
    'why.feature2.title': 'Truly personalised',
    'why.feature2.desc': 'Every chart is studied manually with context from your life situation.',
    'why.feature3.title': 'Private & discreet',
    'why.feature3.desc': 'Your birth details and concerns stay between you and your consultant.',
    'why.feature4.title': 'Remedies with follow-through',
    'why.feature4.desc': 'Practical, tested remedies with guidance on how and when to apply them.',

    // How It Works
    'how.title': 'How it',
    'how.title.highlight': 'works',
    'how.subtitle': 'No confusing packages. Three clear steps from question to clarity.',
    'how.step1.title': 'Pick your service',
    'how.step1.desc': 'Kundli, matchmaking, tarot, vastu, or gemstones — choose what fits your question.',
    'how.step2.title': 'Share birth details',
    'how.step2.desc': 'Date, time, place of birth — or your specific concern if it is a prashna reading.',
    'how.step3.title': 'Receive guidance',
    'how.step3.desc': 'Get your reading on call, WhatsApp, or as a detailed written report with remedies.',
    'how.note': 'Most consultations begin within 24 hours.',
    'how.cta': 'Start now',

    // Home services section
    'home.services.title': 'Consult for',
    'home.services.title.highlight': 'Better Life',
    'home.services.title.suffix': 'Decisions',
    'home.services.all': 'All services',
    'home.services.notSure': 'Not sure which service fits?',
    'home.services.guideYou': "Tell us your concern — we'll guide you.",
    'home.services.askNow': 'Ask now',

    // Ask dialog
    'home.ask.title': 'Connect with Us',
    'home.ask.desc': 'Choose your preferred way to get instant answers to your questions.',
    'home.ask.whatsapp': 'WhatsApp Chat',
    'home.ask.call': 'Direct Call',

    // Matchmaking modal
    'home.match.title': 'Matchmaking Analysis',
    'home.match.desc': 'Enter birth details for both individuals to check compatibility.',
    'home.match.contact': 'Your Contact Details',
    'home.match.person1': 'Person 1 Details',
    'home.match.person2': 'Person 2 Details',
    'home.match.fullName': 'Full Name',
    'home.match.phone': 'Phone',
    'home.match.email': 'Email',
    'home.match.dob': 'Date of Birth',
    'home.match.tob': 'Time of Birth',
    'home.match.pob': 'Place of Birth',
    'home.match.placeholder.location': 'City, Country',
    'home.match.submitting': 'Submitting...',
    'home.match.submit': 'Check Compatibility',

    // Testimonials (homepage)
    'testimonials.heading': 'Stories from',
    'testimonials.heading.highlight': 'real people',
    'testimonials.note': 'Hindi & English consultations. Names shortened for privacy.',
    'testimonials.item.1.name': 'Rahul',
    'testimonials.item.1.location': 'Lucknow',
    'testimonials.item.1.text': 'Aap ki guidance se meri job problem solve hui, 2 mahine me result mila.',
    'testimonials.item.2.name': 'Neha',
    'testimonials.item.2.location': 'Delhi',
    'testimonials.item.2.text': 'Marriage delay issue clear hua, bahut accurate prediction tha.',
    'testimonials.item.3.name': 'Amit',
    'testimonials.item.3.location': 'Mumbai',
    'testimonials.item.3.text': 'Life was stuck, but your remedies worked like magic. Highly recommended!',
    'testimonials.item.4.name': 'Priya',
    'testimonials.item.4.location': 'Bangalore',
    'testimonials.item.4.text': 'Career transition was smooth after your consultation. Thank you!',
    'testimonials.item.5.name': 'Vikram',
    'testimonials.item.5.location': 'Jaipur',
    'testimonials.item.5.text': 'Accurate and very professional service. The best in the field.',

    // Profile extras
    'profile.role': 'Vedic Astrologer & Tarot Reader',
    'profile.years': 'Years',
    'profile.rating': 'Rating',
    'profile.guide': 'Your guide',
    'profile.credential': 'Credential',

    // Mall extras
    'mall.trust.certified': 'Lab certified',
    'mall.trust.energized': 'Energized stones',
    'mall.trust.matched': 'Kundli-matched advice',
    'mall.explore': 'Explore full collection',
    'mall.noProducts': 'No products for this service',
    'mall.visitMall': 'Visit Astro Mall',
    'mall.moreComing': 'More pieces arriving soon',
    'mall.viewMall': 'View mall',
    'mall.newArrivals': 'New arrivals coming',

    // Contact channels
    'contact.channel.call': 'Call',
    'contact.channel.whatsapp': 'WhatsApp',
    'contact.channel.chat': 'Chat with us',
    'contact.channel.email': 'Email',
    'contact.channel.response': 'Response time',
    'contact.channel.responseTime': 'Within 24 hours',
    'contact.channel.location': 'Location',
    'contact.page.title': 'Get in',
    'contact.page.title.highlight': 'touch',
    'contact.page.subtitle': "Tell us what you need — we'll respond within 24 hours with next steps.",
    'contact.page.reachTitle': 'Reach us directly',
    'contact.page.reachSubtitle': 'Pick the channel that works best for you.',
    'contact.page.hours': 'Mon–Sun, 10am–8pm IST',
    'contact.page.whatsappNote': 'Quick queries and instant support',
    'contact.page.locationValue': 'Lucknow, India',
    'contact.page.locationNote': 'Online consultations worldwide',
    'contact.page.replyNote': 'We aim to reply to all enquiries within one business day.',
    'contact.page.faqTitle': 'Common questions',
    'contact.page.faq1.q': 'What is the best time to consult?',
    'contact.page.faq1.a': 'You can consult anytime. Morning hours are traditionally considered auspicious for spiritual consultations.',
    'contact.page.faq2.q': 'How long does a session take?',
    'contact.page.faq2.a': 'Sessions typically range from 45 to 75 minutes depending on the service. See our Services page for details.',
    'contact.page.faq3.q': 'Can I reschedule my appointment?',
    'contact.page.faq3.a': 'Yes — up to 24 hours before your appointment. Contact us by phone or WhatsApp.',

    // About page
    'about.hero.title': 'Ancient wisdom,',
    'about.hero.highlight': 'explained clearly.',
    'about.hero.subtitle': 'Astro Suvid was founded in Lucknow to make Vedic astrology and spiritual guidance accessible, practical, and genuinely useful — for relationships, career, health, and home.',
    'about.pillar1.label': 'Years of practice',
    'about.pillar2.label': 'Consultations',
    'about.pillar3.label': 'Based in India',
    'about.story.title': 'Our story',
    'about.story.p1': 'We started with a simple belief: astrology should empower you to make better decisions, not leave you more confused. Too many seekers were getting generic readings or automated reports — we wanted something different.',
    'about.story.p2': 'Today, Astro Suvid blends Vedic astrology, numerology, tarot, and Vastu into a holistic practice. Every consultation is handled by a trained expert who studies your chart manually and speaks in language you can act on.',
    'about.story.location': 'Lucknow, India — serving clients online worldwide',
    'about.values.title': 'What we stand for',
    'about.values.1.title': 'Clarity over confusion',
    'about.values.1.desc': 'Honest guidance grounded in your chart — not vague promises or fear-based readings.',
    'about.values.2.title': 'Rooted in tradition',
    'about.values.2.desc': 'Authentic Vedic Jyotish, numerology, tarot and Vastu — explained for modern life.',
    'about.values.3.title': 'Warmth with professionalism',
    'about.values.3.desc': 'Every session is compassionate, respectful, and tailored to where you are right now.',
    'about.quote': 'We honour your journey with care — guided by the cycles of the cosmos and the timeless logic of Vedic traditions. Every reading is designed to help you feel seen, supported, and able to move forward.',
    'about.quote.author': '— The Astro Suvid team',
    'about.card1.title': 'Authentic wisdom',
    'about.card1.desc': 'Traditional astrology, tarot, and Vastu insight tied to real-life solutions.',
    'about.card2.title': 'Personal care',
    'about.card2.desc': 'One-on-one guidance tailored to your unique chart and current chapter.',
    'about.card3.title': 'Indian roots',
    'about.card3.desc': 'Proudly based in India, built to serve seekers everywhere.',
    'about.cta.title': 'Ready for a clearer path?',
    'about.cta.subtitle': 'Book a consultation and move forward with confidence.',
    'about.cta.button': 'Contact us',

    // Gemstone grid
    'gemstone.showing': 'Showing',
    'gemstone.product': 'product',
    'gemstone.products': 'products',
    'gemstone.planet.all': 'All Planets',
    'gemstone.planet.sun': 'Sun (Ruby)',
    'gemstone.planet.moon': 'Moon (Pearl)',
    'gemstone.planet.mars': 'Mars (Coral)',
    'gemstone.planet.mercury': 'Mercury (Emerald)',
    'gemstone.planet.jupiter': 'Jupiter (Yellow Sapphire)',
    'gemstone.planet.venus': 'Venus (Diamond/Opal)',
    'gemstone.planet.saturn': 'Saturn (Blue Sapphire)',
    'gemstone.planet.rahu': 'Rahu (Hessonite)',
    'gemstone.planet.ketu': "Ketu (Cat's Eye)",

    // WhatsApp Message
    'whatsapp.message': 'Hello, I am interested in inquiring about the product: {productName}. Price: ₹{price}. Please provide more details.',

    // Product Detail
    'product.details': 'Product Details',
    'product.back': 'Back to Mall',
    'product.description': 'Description',
    'product.authentic_guarantee': '100% Authentic & Energetically Cleansed',
    'product.enquire_whatsapp': 'Enquire on WhatsApp',

    // Gemstone Page
    'gemstone.collection.title': 'Our Premium',
    'gemstone.collection.highlight': 'Collection',
    'gemstone.collection.subtitle': 'Explore our curated selection of authentic, lab-certified gemstones energized for your spiritual journey.',
    'gemstone.search.placeholder': 'Search gemstones...',
    'gemstone.filter.category': 'Category:',
    'gemstone.filter.planet': 'Planetary Filter:',
    'gemstone.filter.all_stones': 'All Stones',
    'gemstone.filter.precious': 'Precious',
    'gemstone.filter.semi_precious': 'Semi-Precious',
    'gemstone.filter.rings': 'Rings & Jewelry',
    'gemstone.empty': 'No gemstones found matching your criteria.',
    'gemstone.reset': 'Reset all filters',
    'gemstone.enquire': 'Enquire Now',

    // Vastu Page
    'vastu.hero.title': 'Vastu Solutions for',
    'vastu.hero.highlight': 'Home, Shop & Office',
    'vastu.hero.subtitle': 'Align your living and working spaces with cosmic energies to invite prosperity, health, and peace without any structural changes.',
    'vastu.hero.home': 'Home Vastu',
    'vastu.hero.business': 'Business Growth',
    'vastu.hero.office': 'Office Harmony',
    'vastu.hero.book': 'Book Vastu Consultation',
    'vastu.hero.whatsapp': 'WhatsApp Now',
    'vastu.hero.success': '98% Success Rate',
    'vastu.hero.success.desc': 'In Energy Correction',
    'vastu.hero.badge': 'Ancient Science of Architecture',

    'vastu.problems.badge': 'Identify the Signs',
    'vastu.problems.title': 'Are You Facing These Challenges?',
    'vastu.problems.subtitle': "Often, the root cause of life's persistent challenges lies in the unbalanced energy of your living or working environment.",
    'vastu.problems.1.title': 'Constant Family Arguments',
    'vastu.problems.1.desc': 'Constant arguments and lack of peace among family members despite your best efforts.',
    'vastu.problems.2.title': 'Business Loss or Stagnation',
    'vastu.problems.2.desc': 'Sudden stagnation in business growth or facing unexpected financial losses.',
    'vastu.problems.3.title': 'Unexplained Health Issues',
    'vastu.problems.3.desc': 'Recurring health problems or low energy levels without any clear medical reason.',
    'vastu.problems.4.title': 'Low Customer Footfall',
    'vastu.problems.4.desc': 'Low footfall in your shop or lack of new projects in your office space.',

    'vastu.process.badge': 'Our Methodology',
    'vastu.process.title': 'What We Do:',
    'vastu.process.highlight': 'Our Expert Approach',
    'vastu.process.subtitle': 'We follow a systematic and scientific approach to Vastu Shastra, focusing on creating harmony without requiring expensive structural changes.',
    'vastu.process.1.title': 'Property Analysis',
    'vastu.process.1.desc': 'Complete Vastu analysis of the property through layout study and energy mapping.',
    'vastu.process.2.title': 'Dosha Identification',
    'vastu.process.2.desc': 'Identify direction-wise Doshas to understand which areas are affecting your life.',
    'vastu.process.3.title': 'No-Demolition Remedies',
    'vastu.process.3.desc': 'Practical remedies without any demolition using colors, elements, and simple placements.',
    'vastu.process.4.title': 'Energy Balancing',
    'vastu.process.4.desc': 'Energy balance techniques (placement / correction) to harmonize your space.',
    'vastu.process.f1': 'Scientific Energy Mapping',
    'vastu.process.f2': 'Practical & Modern Solutions',
    'vastu.process.f3': 'No Structural Demolition',
    'vastu.process.f4': 'Results-Oriented Approach',

    'vastu.types.title': 'Choose Your Consultation Mode',
    'vastu.types.subtitle': 'Whether you are anywhere in the world or right here in our city, we have the perfect consultation mode for you.',
    'vastu.types.online.title': 'Online Vastu Consultation',
    'vastu.types.online.desc': 'Perfect for quick analysis and remote assistance. Get expert advice from the comfort of your home.',
    'vastu.types.online.f1': 'Video / WhatsApp analysis',
    'vastu.types.online.f2': 'Photos / layout analysis',
    'vastu.types.online.f3': 'Remote energy scanning',
    'vastu.types.online.f4': 'Digital correction report',
    'vastu.types.online.btn': 'Book Online Session',
    'vastu.types.online.badge': 'Most Popular',
    'vastu.types.visit.title': 'Physical Visit',
    'vastu.types.visit.desc': 'In-depth on-site inspection for large properties, factories, or complex Vastu issues.',
    'vastu.types.visit.f1': 'On-site inspection',
    'vastu.types.visit.f2': 'Detailed correction plan',
    'vastu.types.visit.f3': 'Personalized interaction',
    'vastu.types.visit.f4': 'Comprehensive remedial setup',
    'vastu.types.visit.btn': 'Request On-Site Visit',

    'vastu.booking.title': 'Book Your Consultation',
    'vastu.booking.subtitle': 'Take the first step towards a balanced and prosperous environment. Fill out the form, and our experts will reach out to you.',
    'vastu.booking.call': 'Call Us',
    'vastu.booking.availability': 'Availability',
    'vastu.booking.availability.desc': 'Mon - Sat: 10AM - 7PM',
    'vastu.booking.quote': '"Alignment with cosmic energies brings peace to mind and prosperity to home."',
    'vastu.booking.name': 'Full Name',
    'vastu.booking.phone': 'Mobile Number',
    'vastu.booking.location': 'Location',
    'vastu.booking.property': 'Property Type',
    'vastu.booking.property.placeholder': 'Select Property Type',
    'vastu.booking.property.home': 'Home / Villa',
    'vastu.booking.property.shop': 'Shop / Showroom',
    'vastu.booking.property.office': 'Office Space',
    'vastu.booking.property.factory': 'Industrial / Factory',
    'vastu.booking.property.land': 'Open Land',
    'vastu.booking.date': 'Preferred Date',
    'vastu.booking.problem': 'Problem Description',
    'vastu.booking.problem.placeholder': 'Tell us about the issues you are facing...',
    'vastu.booking.btn.sending': 'Sending...',
    'vastu.booking.btn.book': 'Book Vastu Consultation',

    // Vedic Astrology Page
    'vedic.hero.badge': 'Ancient Wisdom',
    'vedic.hero.title': 'VEDIC ASTROLOGY',
    'vedic.hero.subtitle': 'Accurate Life Guidance through Vedic Astrology',
    'vedic.intro': 'Vedic Astrology (ज्योतिष शास्त्र) analyzes your life deeply based on birth time, planetary positions, and their influences.',
    'vedic.methodology': 'We combine Janm Kundli + Prashna Kundli + Gochar (Transit) for high accuracy predictions.',
    'vedic.analyze.title': 'What we analyze:',
    'vedic.pillars.janm.title': 'Janm Kundli',
    'vedic.pillars.janm.sub': '(Birth Chart Analysis)',
    'vedic.pillars.janm.desc': 'Life pattern (career, marriage, health, finance), Strengths & weaknesses, Yog & Dosha analysis.',
    'vedic.pillars.prashna.title': 'Prashna Kundli',
    'vedic.pillars.prashna.sub': '(Question-Based Prediction)',
    'vedic.pillars.prashna.desc': 'Instant answers to specific questions like "When will I get a job?" or "Will I win the case?".',
    'vedic.pillars.gochar.title': 'Gochar Kundli',
    'vedic.pillars.gochar.sub': '(Transit Analysis)',
    'vedic.pillars.gochar.desc': 'Impact of current planetary transits and upcoming time (good/bad phase) predictions.',
    'vedic.combined.title': 'Combined Analysis',
    'vedic.combined.desc': 'We combine all three to explain why the current situation is happening, what the future holds, timing of events, and practical remedies (Upay).',
    'vedic.solutions.title': 'Who is it for:',
    'vedic.solutions.career': 'Career Confusion',
    'vedic.solutions.marriage': 'Marriage Delay / Relationship Issues',
    'vedic.solutions.business': 'Business Problems',
    'vedic.solutions.health': 'Health & Mental Stress',
    'vedic.solutions.direction': 'Life Direction Unclear',
    'vedic.deliverables.title': 'What you will get:',
    'vedic.deliverables.1': 'Personalised prediction (Not software based)',
    'vedic.deliverables.2': 'Clear guidance + Timing',
    'vedic.deliverables.3': 'Simple & Practical remedies',
    'vedic.deliverables.4': 'Confidential consultation',
    'vedic.cta.book': 'Book Kundli Analysis',
    'vedic.cta.whatsapp': 'Talk on WhatsApp',

    // Tarot Reading Page
    'tarot.hero.badge': 'Intuitive Guidance',
    'tarot.hero.title': 'TAROT READING',
    'tarot.hero.subtitle': 'Instant Guidance through Tarot Cards',
    'tarot.intro': 'Tarot Reading is an intuitive system where cards help understand your current energy and situation.',
    'tarot.effective': 'It is mainly effective in providing guidance for the present situation + near future.',
    'tarot.process.title': 'What happens in Tarot Reading:',
    'tarot.process.1': 'Cards are drawn based on your question or situation.',
    'tarot.process.2': 'Every card gives a specific meaning and message.',
    'tarot.process.3': 'Reader provides interpretation using intuition + symbolism.',
    'tarot.best_for.title': 'Best for these questions:',
    'tarot.best_for.1': 'Love & Relationship',
    'tarot.best_for.2': 'Confusion / Decision Making',
    'tarot.best_for.3': 'Outcome of a situation',
    'tarot.best_for.4': 'Emotional Clarity',
    'tarot.best_for.5': 'Short-term future guidance',
    'tarot.cta.book': 'Book Tarot Reading',
    'tarot.cta.whatsapp': 'Talk on WhatsApp'
  },
  hi: {
    // Header
    'brand.name.full': 'एस्ट्रो सुविद',
    'brand.name.prefix': 'एस्ट्रो',
    'brand.name.highlight': 'सुविद',
    'nav.home': 'होम',
    'nav.services': 'सेवाएं',
    'nav.blog': 'ब्लॉग',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क',
    'nav.consult': 'अभी परामर्श लें',
    'nav.expert': 'विशेषज्ञ परामर्श',

    // Hero
    'hero.relationship.title': 'सच्चा प्यार और',
    'hero.relationship.title.highlight': 'सुखी वैवाहिक जीवन',
    'hero.relationship.subtitle': 'प्राचीन ज्ञान के माध्यम से अपने प्रेम जीवन और विवाह के बारे में स्पष्टता प्राप्त करें।',
    'hero.career.title': 'करियर में रुकावट?',
    'hero.career.title.highlight': 'ग्रोथ चाहते हैं?',
    'hero.career.subtitle': 'ज्योतिष के माध्यम से अपने करियर में तरक्की और सफलता का रास्ता खोलें।',
    'hero.health.title': 'अपनी सेहत और',
    'hero.health.title.highlight': 'मानसिक स्वास्थ्य सुधारें',
    'hero.health.subtitle': 'प्राचीन ज्ञान के माध्यम से अपने स्वास्थ्य में सुधार और मानसिक शांति प्राप्त करें।',
    'hero.vastu.title': 'घर का वास्तु और',
    'hero.vastu.title.highlight': 'सुख-शांति',
    'hero.vastu.subtitle': 'वास्तु के माध्यम से अपने घर में सुख, शांति और समृद्धि लाएं।',
    'hero.business.title': 'व्यापार वृद्धि और',
    'hero.business.title.highlight': 'धन लाभ',
    'hero.business.subtitle': 'ज्योतिषीय उपायों से अपने व्यापार को बढ़ाएं और अधिक लाभ पाएं।',
    'hero.matchmaking.title': 'कुंडली मिलान और',
    'hero.matchmaking.title.highlight': 'सुखी वैवाहिक जीवन',
    'hero.matchmaking.subtitle': 'गहरी कुंडली मिलान के साथ एक सुखी और सफल वैवाहिक जीवन सुनिश्चित करें।',
    'hero.matrimonial.title': 'अपना आदर्श',
    'hero.matrimonial.title.highlight': 'जीवनसाथी खोजें',
    'hero.matrimonial.subtitle': 'अपने संस्कारों और सितारों के आधार पर सबसे अच्छा जीवनसाथी पाएं।',
    'hero.cta.book': 'परामर्श बुक करें',
    'hero.cta.services': 'सेवाएं देखें',
    'hero.cta.relationship': 'प्रेम परामर्श',
    'hero.cta.career': 'करियर मार्गदर्शन',
    'hero.cta.health': 'स्वास्थ्य परामर्श',
    'hero.cta.vastu': 'वास्तु परामर्श',
    'hero.cta.business': 'व्यापार ज्योतिष',
    'hero.cta.matchmaking': 'मेल जांचें',
    'hero.cta.matrimonial': 'पंजीकरण करें',
    'hero.call': 'कॉल',
    'hero.chat': 'व्हाट्सएप',

    // Services
    'services.title': 'हमारी',
    'services.title.highlight': 'सेवाएं',
    'services.subtitle': 'हम आपके जीवन के सबसे महत्वपूर्ण प्रश्नों के लिए स्पष्टता प्रदान करने के लिए आधुनिक समझ के साथ प्राचीन ज्ञान का मिश्रण करते हैं।',
    'services.sacred': 'हमारी सेवाएं',
    'services.sacred.subtitle': 'आपकी ब्रह्मांडीय यात्रा को रोशन करने के लिए डिज़ाइन की गई व्यापक वैदिक ज्योतिष और टैरो कार्ड रीडिंग',
    'services.includes': 'शामिल है:',
    'services.duration': 'अवधि:',
    'services.ready': 'अपनी यात्रा शुरू करने के लिए तैयार हैं?',
    'services.ready.subtitle': 'उस सेवा को चुनें जो आपकी आत्मा के साथ गूंजती है और ब्रह्मांडीय ज्ञान को अपना मार्गदर्शन करने दें।',
    'services.book': 'अपना सत्र बुक करें',
    'services.explore_all': 'सभी देखें',
    'services.begin_journey': 'अपनी यात्रा शुरू करें',
    'services.our_services': 'हमारी सेवाएं',

    // Service 1: Birth Chart Analysis
    'service.birth.title': 'जन्म कुंडली विश्लेषण',
    'service.birth.desc': 'अपने व्यक्तित्व, शक्तियों और जीवन पथ को समझने के लिए अपनी जन्म कुंडली का गहरा विश्लेषण।',
    'service.birth.f1': 'जन्म के समय ग्रहों की स्थिति',
    'service.birth.f2': 'भाव विश्लेषण और अर्थ',
    'service.birth.f3': 'राशि चक्र की व्याख्या',
    'service.birth.f4': 'रिश्तों के लिए दृष्टि विश्लेषण',
    'service.birth.f5': 'दशा भविष्यवाणियां',
    'service.birth.duration': '60 मिनट',

    // Service 2: Planetary Predictions
    'service.planetary.title': 'ग्रह भविष्यवाणियां',
    'service.planetary.desc': 'आगामी ग्रहों के गोचर और आपके जीवन पर उनके प्रभाव के बारे में जानकारी प्राप्त करें।',
    'service.planetary.f1': 'वर्तमान ग्रहों की चाल',
    'service.planetary.f2': 'आगामी अवसर',
    'service.planetary.f3': 'चुनौतियां और समाधान',
    'service.planetary.f4': 'महत्वपूर्ण निर्णयों के लिए समय',
    'service.planetary.f5': 'उपचारात्मक उपाय (उपाय)',
    'service.planetary.duration': '45 मिनट',

    // Service 3: Career Guidance
    'service.career.title': 'करियर मार्गदर्शन',
    'service.career.desc': 'अपने आदर्श करियर पथ और व्यावसायिक विकास को खोजने में मदद करने के लिए वैदिक अंतर्दृष्टि।',
    'service.career.f1': 'दसवें भाव का विश्लेषण',
    'service.career.f2': 'करियर अनुकूलता',
    'service.career.f3': 'करियर परिवर्तन के लिए सबसे अच्छा समय',
    'service.career.f4': 'व्यापार के अवसर',
    'service.career.f5': 'सफलता के संकेतक',
    'service.career.duration': '50 मिनट',

    // Service 4: Relationship Insights
    'service.relationship.title': 'संबंध अंतर्दृष्टि',
    'service.relationship.desc': 'अपने रिश्ते के पैटर्न और अपने साथी के साथ अनुकूलता को समझें।',
    'service.relationship.f1': 'सिनस्ट्री विश्लेषण',
    'service.relationship.f2': 'अनुकूलता रिपोर्ट',
    'service.relationship.f3': 'प्रतिबद्धताओं के लिए समय',
    'service.relationship.f4': 'पारिवारिक सद्भाव अंतर्दृष्टि',
    'service.relationship.f5': 'चुनौतियों के लिए मार्गदर्शन',
    'service.relationship.duration': '60 मिनट',

    // Service 5: Tarot Card Reading
    'service.tarot.title.main': 'टैरो कार्ड रीडिंग',
    'service.tarot.desc.main': 'आपकी वर्तमान स्थिति और भविष्य के पथ को रोशन करने के लिए टैरो के माध्यम से सहज मार्गदर्शन।',
    'service.tarot.main.f1': 'तीन-कार्ड स्प्रेड',
    'service.tarot.main.f2': 'विस्तृत कार्ड व्याख्या',
    'service.tarot.main.f3': 'जीवन सलाह और मार्गदर्शन',
    'service.tarot.main.f4': 'ऊर्जा समाशोधन अंतर्दृष्टि',
    'service.tarot.main.f5': 'आध्यात्मिक संदेश',
    'service.tarot.main.duration': '45 मिनट',

    // Service 6: Life Purpose Session
    'service.purpose.title': 'जीवन उद्देश्य सत्र',
    'service.purpose.desc': 'वैदिक ज्ञान के माध्यम से अपनी आत्मा के उद्देश्य और जीवन मिशन की खोज करें।',
    'service.purpose.f1': 'नोडल अक्ष विश्लेषण',
    'service.purpose.f2': 'आत्मा के कर्म सबक',
    'service.purpose.f3': 'जीवन उद्देश्य संकेतक',
    'service.purpose.f4': 'आध्यात्मिक विकास पथ',
    'service.purpose.f5': 'पूर्ति रणनीतियाँ',
    'service.purpose.duration': '75 मिनट',

    // Service 1: Vedic Astrology
    'service.vedic.title': 'वैदिक ज्योतिष',
    'service.vedic.desc': 'आपका ब्रह्मांडीय खाका प्राचीन नाक्षत्र गणना और ग्रहों की अवधि के माध्यम से प्रकट हुआ।',
    'service.vedic.f1': 'जन्म कुंडली विश्लेषण',
    'service.vedic.f2': 'ग्रह दशा',
    'service.vedic.f3': 'करियर और धन',
    'service.vedic.f4': 'संबंध अनुकूलता',

    // Service 2: Sacred Tarot
    'service.tarot.title': 'पवित्र टैरो',
    'service.tarot.desc': 'आपकी वर्तमान ऊर्जाओं और मार्गों को रोशन करने के लिए गूढ़ प्रतीकवाद का उपयोग करते हुए सहज मार्गदर्शन।',
    'service.tarot.f1': 'सहज स्प्रेड्स',
    'service.tarot.f2': 'आध्यात्मिक विकास',
    'service.tarot.f3': 'निर्णय स्पष्टता',
    'service.tarot.f4': 'ऊर्जा संरेखण',

    // New Services Section
    'service.kundli.title': 'जन्म कुंडली विश्लेषण',
    'service.kundli.desc': 'अपने जीवन, करियर, विवाह और भविष्य को गहराई से समझें (वैदिक ज्योतिष के माध्यम से)',
    'service.kundli.btn': 'अभी पूछें',
    'service.kundli.details': 'जन्म के समय ग्रहों की स्थिति, भाव विश्लेषण, राशि चक्र की व्याख्या और जीवन के सभी पहलुओं के लिए दशा भविष्यवाणियों सहित आपकी जन्म कुंडली का गहरा विश्लेषण।',

    'service.prashna.title': 'प्रश्न कुंडली',
    'service.prashna.desc': 'अपने विशिष्ट प्रश्नों के उत्तर तुरंत प्राप्त करें',
    'service.prashna.btn': 'अभी पूछें',
    'service.prashna.details': 'होरी ज्योतिष (Prashna Astrology) जो जन्म कुंडली के बिना विशिष्ट प्रश्नों के तत्काल उत्तर प्रदान करती है, जो पूछने के समय ग्रहों की स्थिति पर आधारित होती है।',

    'service.vastu.title': 'वास्तु परामर्श',
    'service.vastu.desc': 'घर / दुकान / कार्यालय समाधान',
    'service.vastu.btn': 'विजिट बुक करें',
    'service.vastu.details': 'सकारात्मक ऊर्जा का प्रवाह, समृद्धि और शांति सुनिश्चित करने के लिए आधुनिक स्थानों पर लागू प्राचीन वास्तुकला ज्ञान।',

    'service.gemstone.title': 'रत्न परामर्श और खरीद',
    'service.gemstone.desc': 'प्रमाणन के साथ सही रत्न प्राप्त करें',
    'service.gemstone.btn': 'पत्थर देखें',
    'service.gemstone.details': 'शक्तियों को बढ़ाने और चुनौतियों को कम करने के लिए आपकी ग्रहों की स्थिति के आधार पर प्रामाणिक, लैब-प्रमाणित रत्नों की व्यक्तिगत सिफारिश।',

    'service.matchmaking.title': 'गुण मिलान विश्लेषण',
    'service.matchmaking.desc': 'सफल विवाह के लिए गहरी अनुकूलता जांच',
    'service.matchmaking.btn': 'अनुकूलता जांचें',
    'service.matchmaking.details': 'दीर्घकालिक वैवाहिक सद्भाव और स्थिरता के लिए व्यापक गुण मिलान और मांगलिक दोष, भकूट और नाड़ी का विश्लेषण।',

    'service.matrimonial.title': 'वैवाहिक सेवाएं',
    'service.matrimonial.desc': 'बस हमारा वैवाहिक फॉर्म भरें और अपना उपयुक्त साथी पाएं',
    'service.matrimonial.btn': 'फॉर्म भरें',
    'service.matrimonial.details': 'एक अनूठा ज्योतिष-आधारित वैवाहिक मंच जहां हम ब्रह्मांडीय अनुकूलता और पारंपरिक मूल्यों के आधार पर प्रोफाइल को फिल्टर करते हैं।',

    'service.business.title': 'व्यापार वृद्धि',
    'service.business.desc': 'व्यापार में सफलता और घाटे से उबरने के लिए ज्योतिषीय मार्गदर्शन प्राप्त करें',
    'service.business.btn': 'व्यापार बढ़ाएं',
    'service.business.details': 'उद्यमियों के लिए रणनीतिक ज्योतिषीय परामर्श, जो शुभ लॉन्चिंग समय, साझेदारी अनुकूलता और वित्तीय सुधार पर केंद्रित है।',

    'service.tarot.title': 'टैरो कार्ड रीडिंग',
    'service.tarot.desc': 'आपकी वर्तमान स्थिति और भविष्य के पथ को रोशन करने के लिए टैरो के माध्यम से सहज मार्गदर्शन',
    'service.tarot.btn': 'बुक नाउ',
    'service.tarot.details': 'गूढ़ प्रतीकवाद और ऊर्जा संरेखण का उपयोग करके रिश्तों, करियर और व्यक्तिगत विकास पर सहज मार्गदर्शन प्रदान करने वाले पवित्र टैरो स्प्रेड।',

    // Business Growth Page
    'business.hero.title': 'व्यापार वृद्धि पेज',
    'business.hero.subtitle': 'ज्योतिष मार्गदर्शन के साथ अपना व्यवसाय बढ़ाएं',
    'business.hero.desc': 'अगर आपका business stuck है या losses हो रहे हैं, तो ये service आपके लिए है -',
    'business.analyze.title': 'हम क्या analyze करते हैं:',
    'business.analyze.point1.title': 'बिजनेस कुंडली',
    'business.analyze.point1.sub': '(मालिक + बिजनेस शुरू होने का समय)',
    'business.analyze.point1.desc': 'मालिक की कुंडली और बिजनेस शुरू होने के समय का व्यापक विश्लेषण।',
    'business.analyze.point2.title': 'वर्तमान दशा और ग्रहों का प्रभाव',
    'business.analyze.point2.desc': 'यह समझना कि वर्तमान ग्रह अवधि आपके व्यावसायिक संचालन को कैसे प्रभावित कर रही है।',
    'business.analyze.point3.title': 'सही मुहूर्त',
    'business.analyze.point3.sub': '(विस्तार / नया काम शुरू करने के लिए)',
    'business.analyze.point3.desc': 'विस्तार या नए कार्य शुरू करने के लिए सबसे शुभ समय खोजना।',
    'business.analyze.point4.title': 'पार्टनरशिप अनुकूलता विश्लेषण',
    'business.analyze.point4.desc': 'दीर्घकालिक सद्भाव और सफलता सुनिश्चित करने के लिए व्यापार भागीदारों का विस्तृत विश्लेषण।',
    'business.analyze.point5.title': 'वित्तीय रुकावट के कारण',
    'business.analyze.point5.desc': 'वित्तीय स्थिरता के पीछे ज्योतिषीय और व्यावहारिक कारणों की पहचान करना।',
    'business.solutions.title': 'हमारे समाधान',
    'business.solutions.subtitle': 'आपके व्यवसाय की सफलता के लिए व्यावहारिक और ज्योतिषीय उपाय।',
    'business.solutions.point1.title': 'हानि से उबरने के उपाय',
    'business.solutions.point1.desc': 'व्यापार घाटे से उबरने और वित्त को स्थिर करने के लिए विशिष्ट ज्योतिषीय उपाय।',
    'business.solutions.point2.title': 'सही समय पर निर्णय मार्गदर्शन',
    'business.solutions.point2.desc': 'सही समय पर सही व्यावसायिक निर्णय लेने में आपकी सहायता के लिए समय-आधारित मार्गदर्शन।',
    'business.solutions.point3.title': 'ग्रोथ बूस्टिंग उपाय',
    'business.solutions.point3.sub': '(व्यावहारिक + ज्योतिषीय)',
    'business.solutions.point3.desc': 'विकास को गति देने के लिए व्यावहारिक व्यावसायिक सलाह और ज्योतिषीय उपायों का मिश्रण।',
    'business.solutions.point4.title': 'बिजनेस नाम / ब्रांडिंग सुझाव',
    'business.solutions.point4.desc': 'व्यावसायिक नामों और ब्रांडिंग के लिए अंक ज्योतिष और ज्योतिषीय सुझाव।',
    'business.feature.badge': 'विशेष विशेषता',
    'business.feature.title': 'केस स्टडी आधारित दृष्टिकोण',
    'business.feature.point': '👉 Real अनुभव के आधार पर practical solutions',
    'business.feature.desc': 'हम केवल सामान्य सलाह नहीं देते हैं। हमारा दृष्टिकोण वास्तविक दुनिया के परिदृश्यों और विभिन्न व्यावसायिक मामलों के प्रमाणित परिणामों पर आधारित है।',
    'business.ideal.title': 'इनके लिए आदर्श',
    'business.ideal.point1': 'दुकान मालिक',
    'business.ideal.point2': 'स्टार्टअप संस्थापक',
    'business.ideal.point3': 'फ्रीलांसर',
    'business.ideal.point4': 'साझेदारी व्यवसाय',
    'business.cta.book': 'बिजनेस विश्लेषण बुक करें',
    'business.cta.whatsapp': 'व्हाट्सएप पर मार्गदर्शन प्राप्त करें',
    'business.whatsapp.message': 'नमस्ते, मैं बिजनेस ग्रोथ कंसल्टेशन में रुचि रखता हूं।',

    // Matrimonial Page
    'matrimonial.hero.badge': 'पावन गठबंधन',
    'matrimonial.hero.title': 'अपना आदर्श जीवनसाथी खोजें',
    'matrimonial.hero.subtitle': '(ज्योतिष-आधारित मिलान)',
    'matrimonial.hero.description': 'यह सिर्फ matrimonial site नहीं है — यह astrology-based filtered matching system है',
    'matrimonial.how.title': 'यह कैसे काम करता है',
    'matrimonial.how.step1': 'यूजर अपना प्रोफाइल रजिस्टर करेगा',
    'matrimonial.how.step2': 'कुंडली विवरण सबमिट करेगा',
    'matrimonial.how.step3': 'मिलान वाले प्रोफाइल शॉर्टलिस्ट होंगे',
    'matrimonial.how.step4': 'आपकी अनुमति के बाद ही डेटा साझा होगा',
    'matrimonial.privacy.title': 'गोपनीयता आश्वासन',
    'matrimonial.privacy.text1': 'आपका डेटा आपकी अनुमति के बिना साझा नहीं किया जाएगा',
    'matrimonial.privacy.text2': 'सुरक्षित और गोपनीय प्रणाली',
    'matrimonial.features.title': 'विशेष विशेषताएं',
    'matrimonial.features.1': 'ज्योतिष-आधारित प्रोफाइल मिलान',
    'matrimonial.features.2': 'सत्यापित प्रोफाइल (मैनुअल चेक)',
    'matrimonial.features.3': 'अंतिम निर्णय से पहले सीधा परामर्श',
    'matrimonial.features.4': 'प्रीमियम मैचमेकिंग सहायता (सशुल्क विकल्प)',
    'matrimonial.cta.register': 'अभी रजिस्टर करें',
    'matrimonial.cta.help': 'मैचमेकिंग सहायता प्राप्त करें',
    'matrimonial.form.title': 'प्रोफाइल पंजीकरण',
    'matrimonial.form.name': 'पूरा नाम',
    'matrimonial.form.dob': 'जन्म तिथि',
    'matrimonial.form.tob': 'जन्म समय',
    'matrimonial.form.pob': 'जन्म स्थान',
    'matrimonial.form.gender': 'लिंग',
    'matrimonial.form.caste': 'जाति / गोत्र',
    'matrimonial.form.height': 'लंबाई',
    'matrimonial.form.weight': 'वजन',
    'matrimonial.form.education': 'शिक्षा',
    'matrimonial.form.profession': 'व्यवसाय',
    'matrimonial.form.location': 'स्थान',
    'matrimonial.form.photo': 'फोटो अपलोड',
    'matrimonial.form.submit': 'प्रोफाइल रजिस्टर करें',

    // Astro Mall
    'mall.title': 'द',
    'mall.title.highlight': 'एस्ट्रो',
    'mall.subtitle': 'प्रीमियम रत्न और पवित्र कलाकृतियाँ, व्यक्तिगत रूप से चुनी गई और आपकी ब्रह्मांडीय यात्रा के लिए ऊर्जावान रूप से शुद्ध की गई।',
    'mall.coming_soon': 'जल्द आ रहा है - पवित्र कलाकृतियाँ',
    'mall.enquire': 'अभी पूछताछ करें',
    'mall.authentic': 'प्रामाणिक',
    'mall.mall': 'मॉल',

    // Footer
    'footer.description': 'आध्यात्मिक पथ पर आपका विश्वसनीय साथी, प्राचीन ज्ञान को आधुनिक दुनिया में लाना।',
    'footer.navigation': 'नेविगेशन',
    'footer.services': 'सेवाएं',
    'footer.guides': 'विशेषज्ञ गाइड',
    'footer.connect': 'जुड़ें',
    'footer.legal': 'कानूनी',
    'footer.address': 'लखनऊ, उत्तर प्रदेश, भारत',
    'footer.rights': 'एस्ट्रो सुविद। सर्वाधिकार सुरक्षित।',
    'footer.crafted': 'आध्यात्मिक विकास के लिए निर्मित',
    'footer.made_with': 'निर्मित',
    'footer.by_team': 'कॉस्मिक टीम द्वारा',

    // Links
    'link.home': 'होम',
    'link.services': 'सेवाएं',
    'link.contact': 'संपर्क',
    'link.horoscope': 'दैनिक राशिफल',
    'link.career': 'करियर ज्योतिष',
    'link.marriage': 'विवाह ज्योतिष',
    'link.kundli': 'कुंडली मिलान',
    'link.vastu': 'वास्तु परामर्श',
    'link.numerology': 'अंक ज्योतिष सेवाएं',
    'link.gemstone': 'रत्न परामर्श',
    'link.business': 'व्यापार वृद्धि',
    'link.tarot': 'टैरो रीडिंग',
    'link.guide1': 'लखनऊ के सर्वश्रेष्ठ वैदिक ज्योतिषी',
    'link.guide2': 'लखनऊ के सर्वश्रेष्ठ टैरो रीडर्स',
    'link.guide3': 'लखनऊ के सर्वश्रेष्ठ ज्योतिषी',
    'link.guide4': 'विश्व स्तर पर सर्वश्रेष्ठ ज्योतिषी',
    'link.privacy': 'गोपनीयता नीति',
    'link.terms': 'नियम और शर्तें',
    'link.cancellation': 'रद्दीकरण और धनवापसी',
    'link.shipping': 'शिपिंग और डिलीवरी',

    // Contact Form
    'contact.title': 'अपनी जिज्ञासा भेजें',
    'contact.subtitle': 'अपनी चिंताओं को साझा करें और ब्रह्मांडीय ऊर्जा को अपना मार्ग प्रशस्त करने दें',
    'contact.success': 'धन्यवाद! आपकी जिज्ञासा प्राप्त हो गई है। हम जल्द ही ब्रह्मांडीय आशीर्वाद के साथ आपसे संपर्क करेंगे।',
    'contact.error.name': 'कृपया अपना नाम दर्ज करें',
    'contact.error.email': 'कृपया एक वैध ईमेल दर्ज करें',
    'contact.error.phone': 'कृपया एक वैध फोन नंबर दर्ज करें',
    'contact.error.service': 'कृपया एक सेवा चुनें',
    'contact.error.message': 'कृपया अपना संदेश दर्ज करें',
    'contact.label.name': 'पूरा नाम *',
    'contact.placeholder.name': 'आपका नाम',
    'contact.label.email': 'ईमेल *',
    'contact.placeholder.email': 'your@email.com',
    'contact.label.phone': 'फोन नंबर *',
    'contact.placeholder.phone': '+91 98765 43210',
    'contact.label.service': 'सेवा *',
    'contact.placeholder.service': 'एक सेवा चुनें',
    'contact.service.vedic': 'वैदिक ज्योतिष परामर्श',
    'contact.service.tarot': 'टैरो कार्ड रीडिंग',
    'contact.service.both': 'दोनों सेवाएं',
    'contact.service.other': 'अन्य पूछताछ',
    'contact.label.message': 'आपका संदेश *',
    'contact.placeholder.message': 'हमें अपनी चिंताओं, प्रश्नों या आप किस मार्गदर्शन की तलाश में हैं, इसके बारे में बताएं...',
    'contact.button.sending': 'भेजा जा रहा है...',
    'contact.button.send': 'जिज्ञासा भेजें',
    'contact.privacy': 'हम आपकी गोपनीयता का सम्मान करते हैं। आपकी जानकारी का उपयोग केवल आपको ब्रह्मांडीय मार्गदर्शन प्रदान करने के लिए किया जाएगा।',

    // Testimonials
    'testimonials.title': 'दिव्य',
    'testimonials.title.highlight': 'आशीर्वाद',
    'testimonials.subtitle': 'उन लोगों की आवाजें जिनके पथ ब्रह्मांडीय ज्ञान से आलोकित हुए हैं।',
    'testimonials.1.name': 'प्रिया शर्मा',
    'testimonials.1.role': 'व्यवसाय मालिक',
    'testimonials.1.text': 'दर्शी की वैदिक ज्योतिष रीडिंग ने मुझे करियर के चुनौतीपूर्ण बदलाव के दौरान वह स्पष्टता दी जिसकी मुझे आवश्यकता थी। अंतर्दृष्टि उल्लेखनीय रूप से सटीक और परिवर्तनकारी थी।',
    'testimonials.2.name': 'अंजलि वर्मा',
    'testimonials.2.role': 'स्वास्थ्य देखभाल पेशेवर',
    'testimonials.2.text': 'मेरे रिश्तों और व्यक्तिगत विकास को समझने में टैरो रीडिंग अविश्वसनीय रूप से मददगार रही है। दर्शी का अंतर्ज्ञान वास्तव में असाधारण है।',
    'testimonials.3.name': 'नेहा पटेल',
    'testimonials.3.role': 'रचनात्मक पेशेवर',
    'testimonials.3.text': 'जन्म कुंडली विश्लेषण ने मुझे अपनी शक्तियों और क्षमता की गहरी समझ प्रदान की। मैंने अपने उद्देश्य के साथ इतना संरेखित कभी महसूस नहीं किया।',

    // Astrologer Profile
    'profile.title': 'मिलें',
    'profile.title.highlight': 'दर्शी',
    'profile.description': 'एक समर्पित वैदिक ज्योतिषी और टैरो रीडर, जिन्हें जीवन की ब्रह्मांडीय यात्रा के माध्यम से साधकों का मार्गदर्शन करने में एक दशक से अधिक का अनुभव है। दर्शी आपके अद्वितीय पथ के अनुरूप परिवर्तनकारी रीडिंग प्रदान करने के लिए प्राचीन वैदिक ज्ञान को सहज आध्यात्मिक मार्गदर्शन के साथ जोड़ती हैं।',
    'profile.cred1.title': 'वैदिक विशेषज्ञ',
    'profile.cred1.desc': 'नाक्षत्र गणना और ग्रहों की अवधि (दशा) में विशेषज्ञ।',
    'profile.cred2.title': 'प्रमाणित मास्टर',
    'profile.cred2.desc': 'शास्त्रीय टैरो प्रतीकवाद और सहज स्प्रेड्स में गहराई से प्रशिक्षित।',
    'profile.expertise.title': 'मुख्य विशेषज्ञता',
    'profile.expertise.1': 'करियर मार्गदर्शन',
    'profile.expertise.2': 'रिश्तों की अंतर्दृष्टि',
    'profile.expertise.3': 'जीवन का उद्देश्य',
    'profile.expertise.4': 'आध्यात्मिक विकास',
    'profile.expertise.5': 'ऊर्जा संरेखण',

    // CTA Banner
    'cta.title': 'अपने रहस्यों को अनलॉक करें',
    'cta.title.highlight': 'कुंडली',
    'cta.subtitle': 'करियर, विवाह और जीवन के सबसे बड़े सवालों के लिए विशेषज्ञ मार्गदर्शन प्राप्त करें। व्यक्तिगत परामर्श के लिए लखनऊ के सबसे भरोसेमंद ज्योतिषियों से जुड़ें।',
    'cta.button.book': 'परामर्श बुक करें',
    'cta.button.whatsapp': 'व्हाट्सएप',
    'cta.trusted': 'दुनिया भर में 500+ साधकों द्वारा भरोसा किया गया',
    'cta.chart.title': 'आपकी कुंडली',
    'cta.chart.subtitle': '12 भाव · 9 ग्रह',
    'cta.response.label': 'जवाब मिलेगा',
    'cta.response.value': '24 घंटे में',

    // Nav language
    'nav.language': 'भाषा',

    // PWA install
    'pwa.bar.title': 'एस्ट्रो सुविद ऐप इंस्टॉल करें',
    'pwa.bar.subtitle': 'परामर्श और राशिफल तक तुरंत पहुँच',
    'pwa.modal.title': 'सबसे अच्छे अनुभव के लिए ऐप इंस्टॉल करें',
    'pwa.modal.subtitle': 'ज्योतिष सेवाएं, बुकिंग और अपडेट — सीधे होम स्क्रीन से तुरंत एक्सेस करें।',
    'pwa.install': 'इंस्टॉल',
    'pwa.installNow': 'अभी ऐप इंस्टॉल करें',
    'pwa.installing': 'इंस्टॉल हो रहा है…',
    'pwa.later': 'बाद में',
    'pwa.dismiss': 'दोबारा न दिखाएं',
    'pwa.benefit1': 'होम स्क्रीन से एक टैप में खुलें',
    'pwa.benefit2': 'तेज़ लोडिंग और ऐप जैसा अनुभव',
    'pwa.benefit3': 'परामर्श और सेवाओं की आसान बुकिंग',
    'pwa.ios.step1': 'Safari में नीचे Share बटन पर टैप करें',
    'pwa.ios.step2': 'नीचे स्क्रॉल करके "Add to Home Screen" चुनें',
    'pwa.ios.step3': 'Add पर टैप करें — एस्ट्रो सुविद होम स्क्रीन पर दिखेगा',
    'pwa.android.fallback': 'ब्राउज़र मेनू (⋮) में जाएं और "Install app" या "Add to Home screen" चुनें।',

    // Footer consult
    'footer.consult.title': 'परामर्श',
    'footer.consult.desc': 'करियर, विवाह, स्वास्थ्य या रत्नों के बारे में सवाल हैं? हमारी टीम से सीधे बात करें।',
    'footer.whatsapp': 'व्हाट्सएप',

    // Why Choose Us
    'why.title': 'ऐसा मार्गदर्शन जो',
    'why.title.highlight': 'मानवीय',
    'why.title.suffix': ' लगे, मशीन से नहीं बना।',
    'why.subtitle': 'प्राचीन ज्योतिष ज्ञान, सरल भाषा में — देखभाल, स्पष्टता और ऐसे उपाय जो आप वास्तव में अपना सकते हैं।',
    'why.stat1.label': 'वर्षों का अनुभव',
    'why.stat2.label': 'परामर्श पूरे किए',
    'why.stat3.label': 'गोपनीय सत्र',
    'why.feature1.title': 'योग्य विशेषज्ञ टीम',
    'why.feature1.desc': 'प्रशिक्षित वैदिक ज्योतिषियों द्वारा रीडिंग — स्वचालित सॉफ्टवेयर आउटपुट नहीं।',
    'why.feature2.title': 'वास्तव में व्यक्तिगत',
    'why.feature2.desc': 'हर कुंडली आपकी जीवन स्थिति के संदर्भ में मैन्युअल रूप से अध्ययन की जाती है।',
    'why.feature3.title': 'निजी और गोपनीय',
    'why.feature3.desc': 'आपके जन्म विवरण और चिंताएं केवल आप और आपके परामर्शदाता के बीच रहती हैं।',
    'why.feature4.title': 'उपायों के साथ मार्गदर्शन',
    'why.feature4.desc': 'व्यावहारिक, परखे हुए उपाय — कैसे और कब अपनाएं, इसकी पूरी जानकारी।',

    // How It Works
    'how.title': 'यह कैसे',
    'how.title.highlight': 'काम करता है',
    'how.subtitle': 'कोई भ्रमित करने वाले पैकेज नहीं। सवाल से समाधान तक तीन स्पष्ट कदम।',
    'how.step1.title': 'सेवा चुनें',
    'how.step1.desc': 'कुंडली, मिलान, टैरो, वास्तु या रत्न — अपने सवाल के अनुसार चुनें।',
    'how.step2.title': 'जन्म विवरण साझा करें',
    'how.step2.desc': 'जन्म की तारीख, समय, स्थान — या प्रश्न कुंडली के लिए अपनी विशिष्ट चिंता।',
    'how.step3.title': 'मार्गदर्शन प्राप्त करें',
    'how.step3.desc': 'कॉल, व्हाट्सएप या विस्तृत लिखित रिपोर्ट के साथ उपाय प्राप्त करें।',
    'how.note': 'अधिकांश परामर्श 24 घंटे के भीतर शुरू हो जाते हैं।',
    'how.cta': 'अभी शुरू करें',

    // Home services section
    'home.services.title': 'बेहतर जीवन',
    'home.services.title.highlight': 'निर्णयों',
    'home.services.title.suffix': 'के लिए परामर्श',
    'home.services.all': 'सभी सेवाएं',
    'home.services.notSure': 'पता नहीं कौन सी सेवा सही है?',
    'home.services.guideYou': 'अपनी चिंता बताएं — हम आपका मार्गदर्शन करेंगे।',
    'home.services.askNow': 'अभी पूछें',

    // Ask dialog
    'home.ask.title': 'हमसे जुड़ें',
    'home.ask.desc': 'अपने सवालों के तुरंत जवाब पाने का अपना पसंदीदा तरीका चुनें।',
    'home.ask.whatsapp': 'व्हाट्सएप चैट',
    'home.ask.call': 'सीधी कॉल',

    // Matchmaking modal
    'home.match.title': 'कुंडली मिलान विश्लेषण',
    'home.match.desc': 'अनुकूलता जांचने के लिए दोनों व्यक्तियों का जन्म विवरण दर्ज करें।',
    'home.match.contact': 'आपका संपर्क विवरण',
    'home.match.person1': 'व्यक्ति 1 का विवरण',
    'home.match.person2': 'व्यक्ति 2 का विवरण',
    'home.match.fullName': 'पूरा नाम',
    'home.match.phone': 'फोन',
    'home.match.email': 'ईमेल',
    'home.match.dob': 'जन्म तिथि',
    'home.match.tob': 'जन्म समय',
    'home.match.pob': 'जन्म स्थान',
    'home.match.placeholder.location': 'शहर, देश',
    'home.match.submitting': 'भेजा जा रहा है...',
    'home.match.submit': 'अनुकूलता जांचें',

    // Testimonials (homepage)
    'testimonials.heading': 'वास्तविक लोगों की',
    'testimonials.heading.highlight': 'कहानियां',
    'testimonials.note': 'हिंदी और अंग्रेजी परामर्श। गोपनीयता के लिए नाम संक्षिप्त किए गए।',
    'testimonials.item.1.name': 'राहुल',
    'testimonials.item.1.location': 'लखनऊ',
    'testimonials.item.1.text': 'आपकी मार्गदर्शन से मेरी नौकरी की समस्या हल हुई, 2 महीने में परिणाम मिला।',
    'testimonials.item.2.name': 'नेहा',
    'testimonials.item.2.location': 'दिल्ली',
    'testimonials.item.2.text': 'विवाह में देरी का मुद्दा स्पष्ट हुआ, बहुत सटीक भविष्यवाणी थी।',
    'testimonials.item.3.name': 'अमित',
    'testimonials.item.3.location': 'मुंबई',
    'testimonials.item.3.text': 'जीवन अटका हुआ था, लेकिन आपके उपायों ने जादू की तरह काम किया। अत्यधिक अनुशंसित!',
    'testimonials.item.4.name': 'प्रिया',
    'testimonials.item.4.location': 'बैंगलोर',
    'testimonials.item.4.text': 'आपके परामर्श के बाद करियर बदलाव सुचारू रहा। धन्यवाद!',
    'testimonials.item.5.name': 'विक्रम',
    'testimonials.item.5.location': 'जयपुर',
    'testimonials.item.5.text': 'सटीक और बहुत पेशेवर सेवा। इस क्षेत्र में सर्वश्रेष्ठ।',

    // Profile extras
    'profile.role': 'वैदिक ज्योतिषी और टैरो रीडर',
    'profile.years': 'वर्ष',
    'profile.rating': 'रेटिंग',
    'profile.guide': 'आपका मार्गदर्शक',
    'profile.credential': 'प्रमाणपत्र',

    // Mall extras
    'mall.trust.certified': 'लैब प्रमाणित',
    'mall.trust.energized': 'ऊर्जावान रत्न',
    'mall.trust.matched': 'कुंडली-आधारित सलाह',
    'mall.explore': 'पूरा संग्रह देखें',
    'mall.noProducts': 'इस सेवा के लिए कोई उत्पाद नहीं',
    'mall.visitMall': 'एस्ट्रो मॉल देखें',
    'mall.moreComing': 'और रत्न जल्द आ रहे हैं',
    'mall.viewMall': 'मॉल देखें',
    'mall.newArrivals': 'नए उत्पाद आ रहे हैं',

    // Contact channels
    'contact.channel.call': 'कॉल',
    'contact.channel.whatsapp': 'व्हाट्सएप',
    'contact.channel.chat': 'हमसे चैट करें',
    'contact.channel.email': 'ईमेल',
    'contact.channel.response': 'जवाब का समय',
    'contact.channel.responseTime': '24 घंटे के भीतर',
    'contact.channel.location': 'स्थान',
    'contact.page.title': 'संपर्क',
    'contact.page.title.highlight': 'करें',
    'contact.page.subtitle': 'हमें बताएं आपको क्या चाहिए — हम 24 घंटे के भीतर अगले कदम के साथ जवाब देंगे।',
    'contact.page.reachTitle': 'सीधे संपर्क करें',
    'contact.page.reachSubtitle': 'अपने लिए सबसे सुविधाजनक माध्यम चुनें।',
    'contact.page.hours': 'सोम–रवि, सुबह 10–शाम 8 बजे IST',
    'contact.page.whatsappNote': 'त्वरित प्रश्न और तुरंत सहायता',
    'contact.page.locationValue': 'लखनऊ, भारत',
    'contact.page.locationNote': 'ऑनलाइन परामर्श दुनिया भर में',
    'contact.page.replyNote': 'हम सभी पूछताछ का एक कार्य दिवस के भीतर जवाब देने का प्रयास करते हैं।',
    'contact.page.faqTitle': 'आम सवाल',
    'contact.page.faq1.q': 'परामर्श के लिए सबसे अच्छा समय क्या है?',
    'contact.page.faq1.a': 'आप कभी भी परामर्श ले सकते हैं। पारंपरिक रूप से सुबह के समय को आध्यात्मिक परामर्श के लिए शुभ माना जाता है।',
    'contact.page.faq2.q': 'सत्र में कितना समय लगता है?',
    'contact.page.faq2.a': 'सेवा के अनुसार सत्र आमतौर पर 45 से 75 मिनट तक होते हैं। विवरण के लिए हमारी सेवाएं पृष्ठ देखें।',
    'contact.page.faq3.q': 'क्या मैं अपनी नियुक्ति पुनर्निर्धारित कर सकता/सकती हूं?',
    'contact.page.faq3.a': 'हां — अपनी नियुक्ति से 24 घंटे पहले तक। फोन या व्हाट्सएप से संपर्क करें।',

    // About page
    'about.hero.title': 'प्राचीन ज्ञान,',
    'about.hero.highlight': 'स्पष्ट भाषा में।',
    'about.hero.subtitle': 'एस्ट्रो सुविद की स्थापना लखनऊ में वैदिक ज्योतिष और आध्यात्मिक मार्गदर्शन को सुलभ, व्यावहारिक और वास्तव में उपयोगी बनाने के लिए की गई — रिश्तों, करियर, स्वास्थ्य और घर के लिए।',
    'about.pillar1.label': 'वर्षों का अभ्यास',
    'about.pillar2.label': 'परामर्श',
    'about.pillar3.label': 'भारत में स्थित',
    'about.story.title': 'हमारी कहानी',
    'about.story.p1': 'हमने एक सरल विश्वास के साथ शुरुआत की: ज्योतिष को आपको बेहतर निर्णय लेने में सशक्त बनाना चाहिए, न कि और अधिक भ्रमित। बहुत से साधक सामान्य रीडिंग या स्वचालित रिपोर्ट पा रहे थे — हम कुछ अलग चाहते थे।',
    'about.story.p2': 'आज, एस्ट्रो सुविद वैदिक ज्योतिष, अंक ज्योतिष, टैरो और वास्तु को एक समग्र अभ्यास में मिलाता है। हर परामर्श एक प्रशिक्षित विशेषज्ञ द्वारा संभाला जाता है जो आपकी कुंडली का मैन्युअल अध्ययन करता है और ऐसी भाषा में बोलता है जिस पर आप कार्य कर सकें।',
    'about.story.location': 'लखनऊ, भारत — दुनिया भर में ऑनलाइन ग्राहकों की सेवा',
    'about.values.title': 'हम किसके लिए खड़े हैं',
    'about.values.1.title': 'भ्रम पर स्पष्टता',
    'about.values.1.desc': 'आपकी कुंडली पर आधारित ईमानदार मार्गदर्शन — अस्पष्ट वादे या भय पर आधारित रीडिंग नहीं।',
    'about.values.2.title': 'परंपरा में निहित',
    'about.values.2.desc': 'प्रामाणिक वैदिक ज्योतिष, अंक ज्योतिष, टैरो और वास्तु — आधुनिक जीवन के लिए समझाया गया।',
    'about.values.3.title': 'पेशेवरता के साथ स्नेह',
    'about.values.3.desc': 'हर सत्र करुणामय, सम्मानजनक और आपकी वर्तमान स्थिति के अनुरूप है।',
    'about.quote': 'हम आपकी यात्रा का सम्मान करते हुए देखभाल करते हैं — ब्रह्मांडीय चक्रों और वैदिक परंपराओं के कालातीत तर्क द्वारा मार्गदर्शित। हर रीडिंग आपको समझा हुआ, समर्थित और आगे बढ़ने में सक्षम महसूस कराने के लिए बनाई जाती है।',
    'about.quote.author': '— एस्ट्रो सुविद टीम',
    'about.card1.title': 'प्रामाणिक ज्ञान',
    'about.card1.desc': 'वास्तविक जीवन समाधानों से जुड़ी पारंपरिक ज्योतिष, टैरो और वास्तु अंतर्दृष्टि।',
    'about.card2.title': 'व्यक्तिगत देखभाल',
    'about.card2.desc': 'आपकी अद्वितीय कुंडली और वर्तमान अध्याय के अनुरूप एक-पर-एक मार्गदर्शन।',
    'about.card3.title': 'भारतीय जड़ें',
    'about.card3.desc': 'गर्व से भारत में स्थित, हर जगह साधकों की सेवा के लिए निर्मित।',
    'about.cta.title': 'स्पष्ट मार्ग के लिए तैयार हैं?',
    'about.cta.subtitle': 'परामर्श बुक करें और आत्मविश्वास के साथ आगे बढ़ें।',
    'about.cta.button': 'संपर्क करें',

    // Gemstone grid
    'gemstone.showing': 'दिखा रहे हैं',
    'gemstone.product': 'उत्पाद',
    'gemstone.products': 'उत्पाद',
    'gemstone.planet.all': 'सभी ग्रह',
    'gemstone.planet.sun': 'सूर्य (माणिक)',
    'gemstone.planet.moon': 'चंद्र (मोती)',
    'gemstone.planet.mars': 'मंगल (मूंगा)',
    'gemstone.planet.mercury': 'बुध (पन्ना)',
    'gemstone.planet.jupiter': 'गुरु (पुखराज)',
    'gemstone.planet.venus': 'शुक्र (हीरा/ओपल)',
    'gemstone.planet.saturn': 'शनि (नीलम)',
    'gemstone.planet.rahu': 'राहु (गोमेद)',
    'gemstone.planet.ketu': 'केतु (लहसुनिया)',

    // WhatsApp Message
    'whatsapp.message': 'नमस्ते, मैं इस उत्पाद के बारे में पूछताछ करने में रुचि रखता हूं: {productName}। मूल्य: ₹{price}। कृपया अधिक विवरण प्रदान करें।',

    // Product Detail
    'product.details': 'उत्पाद विवरण',
    'product.back': 'मॉल पर वापस जाएं',
    'product.description': 'विवरण',
    'product.authentic_guarantee': '100% प्रामाणिक और ऊर्जावान रूप से शुद्ध',
    'product.enquire_whatsapp': 'व्हाट्सएप पर पूछताछ करें',

    // Gemstone Page
    'gemstone.collection.title': 'हमारा प्रीमियम',
    'gemstone.collection.highlight': 'कलेक्शन',
    'gemstone.collection.subtitle': 'आपकी आध्यात्मिक यात्रा के लिए ऊर्जावान और लैब-प्रमाणित रत्नों के हमारे चुनिंदा संग्रह को देखें।',
    'gemstone.search.placeholder': 'रत्न खोजें...',
    'gemstone.filter.category': 'श्रेणी:',
    'gemstone.filter.planet': 'ग्रह फिल्टर:',
    'gemstone.filter.all_stones': 'सभी रत्न',
    'gemstone.filter.precious': 'कीमती',
    'gemstone.filter.semi_precious': 'अर्ध-कीमती',
    'gemstone.filter.rings': 'अंगूठियां और आभूषण',
    'gemstone.empty': 'आपके मानदंडों से मेल खाने वाला कोई रत्न नहीं मिला।',
    'gemstone.reset': 'सभी फिल्टर रीसेट करें',
    'gemstone.enquire': 'अभी पूछताछ करें',

    // Vastu Page
    'vastu.hero.title': 'वास्तु समाधान',
    'vastu.hero.highlight': 'घर, दुकान और कार्यालय के लिए',
    'vastu.hero.subtitle': 'बिना किसी संरचनात्मक परिवर्तन के समृद्धि, स्वास्थ्य और शांति को आमंत्रित करने के लिए अपने रहने और काम करने के स्थानों को ब्रह्मांडीय ऊर्जा के साथ संरेखित करें।',
    'vastu.hero.home': 'घर का वास्तु',
    'vastu.hero.business': 'व्यवसाय विकास',
    'vastu.hero.office': 'कार्यालय सद्भाव',
    'vastu.hero.book': 'वास्तु परामर्श बुक करें',
    'vastu.hero.whatsapp': 'अभी व्हाट्सएप करें',
    'vastu.hero.success': '98% सफलता दर',
    'vastu.hero.success.desc': 'ऊर्जा सुधार में',
    'vastu.hero.badge': 'वास्तुकला का प्राचीन विज्ञान',

    'vastu.problems.badge': 'संकेतों को पहचानें',
    'vastu.problems.title': 'क्या आपको ये समस्याएं आ रही हैं?',
    'vastu.problems.subtitle': 'अक्सर, जीवन की निरंतर चुनौतियों का मूल कारण आपके रहने या काम करने के माहौल की असंतुलित ऊर्जा में निहित होता है।',
    'vastu.problems.1.title': 'घर में लगातार झगड़े',
    'vastu.problems.1.desc': 'आपके सर्वोत्तम प्रयासों के बावजूद परिवार के सदस्यों के बीच लगातार बहस और शांति की कमी।',
    'vastu.problems.2.title': 'बिज़नेस में नुकसान या रुकावट',
    'vastu.problems.2.desc': 'व्यापार वृद्धि में अचानक ठहराव या अप्रत्याशित वित्तीय नुकसान का सामना करना।',
    'vastu.problems.3.title': 'बिना कारण स्वास्थ्य समस्याएं',
    'vastu.problems.3.desc': 'बिना किसी स्पष्ट चिकित्सा कारण के बार-बार स्वास्थ्य समस्याएं या निम्न ऊर्जा स्तर।',
    'vastu.problems.4.title': 'ग्राहकों की कमी',
    'vastu.problems.4.desc': 'आपकी दुकान में कम फुटफॉल या आपके कार्यालय स्थान में नई परियोजनाओं की कमी।',

    'vastu.process.badge': 'हमारी कार्यप्रणाली',
    'vastu.process.title': 'हम क्या करेंगे:',
    'vastu.process.highlight': 'हमारा विशेषज्ञ दृष्टिकोण',
    'vastu.process.subtitle': 'हम वास्तु शास्त्र के लिए एक व्यवस्थित और वैज्ञानिक दृष्टिकोण का पालन करते हैं, जो महंगे संरचनात्मक परिवर्तनों की आवश्यकता के बिना सद्भाव बनाने पर ध्यान केंद्रित करते हैं।',
    'vastu.process.1.title': 'संपत्ति विश्लेषण',
    'vastu.process.1.desc': 'लेआउट अध्ययन और ऊर्जा मानचित्रण के माध्यम से संपत्ति का पूर्ण वास्तु विश्लेषण।',
    'vastu.process.2.title': 'दोष पहचान',
    'vastu.process.2.desc': 'यह समझने के लिए कि कौन से क्षेत्र आपके जीवन को प्रभावित कर रहे हैं, दिशा वार दोषों की पहचान करें।',
    'vastu.process.3.title': 'बिना तोड़-फोड़ के उपचार',
    'vastu.process.3.desc': 'रंगों, तत्वों और सरल प्लेसमेंट का उपयोग करके बिना किसी तोड़-फोड़ के व्यावहारिक उपचार।',
    'vastu.process.4.title': 'ऊर्जा संतुलन',
    'vastu.process.4.desc': 'आपके स्थान को सामंजस्यपूर्ण बनाने के लिए ऊर्जा संतुलन तकनीक (प्लेसमेंट / सुधार)।',
    'vastu.process.f1': 'वैज्ञानिक ऊर्जा मानचित्रण',
    'vastu.process.f2': 'व्यावहारिक और आधुनिक समाधान',
    'vastu.process.f3': 'कोई संरचनात्मक तोड़-फोड़ नहीं',
    'vastu.process.f4': 'परिणामोन्मुखी दृष्टिकोण',

    'vastu.types.title': 'अपना परामर्श मोड चुनें',
    'vastu.types.subtitle': 'चाहे आप दुनिया में कहीं भी हों या ठीक यहीं हमारे शहर में, हमारे पास आपके लिए सही परामर्श मोड है।',
    'vastu.types.online.title': 'ऑनलाइन वास्तु परामर्श',
    'vastu.types.online.desc': 'त्वरित विश्लेषण और दूरस्थ सहायता के लिए बिल्कुल सही। अपने घर के आराम से विशेषज्ञ की सलाह लें।',
    'vastu.types.online.f1': 'वीडियो / व्हाट्सएप विश्लेषण',
    'vastu.types.online.f2': 'फोटो / लेआउट विश्लेषण',
    'vastu.types.online.f3': 'रिमोट ऊर्जा स्कैनिंग',
    'vastu.types.online.f4': 'डिजिटल सुधार रिपोर्ट',
    'vastu.types.online.btn': 'ऑनलाइन सत्र बुक करें',
    'vastu.types.online.badge': 'सबसे लोकप्रिय',
    'vastu.types.visit.title': 'भौतिक विजिट',
    'vastu.types.visit.desc': 'बड़ी संपत्तियों, कारखानों या जटिल वास्तु मुद्दों के लिए गहन ऑन-साइट निरीक्षण।',
    'vastu.types.visit.f1': 'ऑन-साइट निरीक्षण',
    'vastu.types.visit.f2': 'विस्तृत सुधार योजना',
    'vastu.types.visit.f3': 'व्यक्तिगत बातचीत',
    'vastu.types.visit.f4': 'व्यापक उपचारात्मक सेटअप',
    'vastu.types.visit.btn': 'ऑन-साइट विजिट का अनुरोध करें',

    'vastu.booking.title': 'अपना परामर्श बुक करें',
    'vastu.booking.subtitle': 'एक संतुलित और समृद्ध वातावरण की ओर पहला कदम उठाएं। फॉर्म भरें, और हमारे विशेषज्ञ आपसे संपर्क करेंगे।',
    'vastu.booking.call': 'हमें कॉल करें',
    'vastu.booking.availability': 'उपलब्धता',
    'vastu.booking.availability.desc': 'सोम - शनि: सुबह 10 बजे - शाम 7 बजे',
    'vastu.booking.quote': '"ब्रह्मांडीय ऊर्जाओं के साथ संरेखण मन को शांति और घर में समृद्धि लाता है।"',
    'vastu.booking.name': 'पूरा नाम',
    'vastu.booking.phone': 'मोबाइल नंबर',
    'vastu.booking.location': 'स्थान',
    'vastu.booking.property': 'संपत्ति का प्रकार',
    'vastu.booking.property.placeholder': 'संपत्ति का प्रकार चुनें',
    'vastu.booking.property.home': 'घर / विला',
    'vastu.booking.property.shop': 'दुकान / शोरूम',
    'vastu.booking.property.office': 'कार्यालय स्थान',
    'vastu.booking.property.factory': 'औद्योगिक / कारखाना',
    'vastu.booking.property.land': 'खुली जमीन',
    'vastu.booking.date': 'पसंदीदा तारीख',
    'vastu.booking.problem': 'समस्या का विवरण',
    'vastu.booking.problem.placeholder': 'हमें उन समस्याओं के बारे में बताएं जिनका आप सामना कर रहे हैं...',
    'vastu.booking.btn.sending': 'भेजा जा रहा है...',
    'vastu.booking.btn.book': 'वास्तु परामर्श बुक करें',

    // Vedic Astrology Page
    'vedic.hero.badge': 'प्राचीन ज्ञान',
    'vedic.hero.title': 'वैदिक ज्योतिष',
    'vedic.hero.subtitle': 'वैदिक ज्योतिष के माध्यम से सटीक जीवन मार्गदर्शन',
    'vedic.intro': 'वैदिक ज्योतिष (ज्योतिष शास्त्र) आपके जन्म समय, ग्रहों की स्थिति और उनके प्रभाव के आधार पर आपकी life का deep analysis करता है',
    'vedic.methodology': 'इसमें हम Janm Kundli + Prashna Kundli + Gochar (Transit) — तीनों को मिलाकर prediction करते हैं, जिससे accuracy बढ़ती है',
    'vedic.analyze.title': 'हम क्या analyze करते हैं:',
    'vedic.pillars.janm.title': 'जन्म कुंडली',
    'vedic.pillars.janm.sub': '(Janm Kundli Analysis)',
    'vedic.pillars.janm.desc': 'Life pattern (career, marriage, health, finance), Strengths & weaknesses, Yog & Dosha analysis.',
    'vedic.pillars.prashna.title': 'प्रश्न कुंडली',
    'vedic.pillars.prashna.sub': '(Question-Based Prediction)',
    'vedic.pillars.prashna.desc': 'Specific question का instant answer। उदाहरण: job लगेगी या नहीं? case जीता जाएगा या नहीं?',
    'vedic.pillars.gochar.title': 'गोचर कुंडली',
    'vedic.pillars.gochar.sub': '(Transit Analysis)',
    'vedic.pillars.gochar.desc': 'वर्तमान ग्रहों का असर, Upcoming time (good / bad phase prediction)।',
    'vedic.combined.title': 'Combined Analysis',
    'vedic.combined.desc': 'हम तीनों को combine करके बताते हैं: Current situation क्यों चल रही है, Future में क्या होने वाला है, सही समय और practical remedies (उपाय)।',
    'vedic.solutions.title': 'किन लोगों के लिए useful:',
    'vedic.solutions.career': 'Career confusion',
    'vedic.solutions.marriage': 'Marriage delay / relationship issues',
    'vedic.solutions.business': 'Business problems',
    'vedic.solutions.health': 'Health & मानसिक stress',
    'vedic.solutions.direction': 'Life direction unclear',
    'vedic.deliverables.title': 'आपको क्या मिलेगा:',
    'vedic.deliverables.1': '✔ Personalised prediction (software based नहीं)',
    'vedic.deliverables.2': '✔ Clear guidance + timing',
    'vedic.deliverables.3': '✔ Simple & practical remedies',
    'vedic.deliverables.4': '✔ Confidential consultation',
    'vedic.cta.book': 'Book Kundli Analysis',
    'vedic.cta.whatsapp': 'Talk on WhatsApp',

    // Tarot Reading Page
    'tarot.hero.badge': 'सहज मार्गदर्शन',
    'tarot.hero.title': 'टैरो रीडिंग',
    'tarot.hero.subtitle': 'टैरो कार्ड के माध्यम से त्वरित मार्गदर्शन',
    'tarot.intro': 'Tarot Reading एक intuitive system है जिसमें cards के माध्यम से आपकी current energy और situation को समझा जाता है',
    'tarot.effective': 'यह mainly present situation + near future guidance देने में effective होता है',
    'tarot.process.title': 'Tarot Reading में क्या होता है:',
    'tarot.process.1': 'आपके question या situation के अनुसार cards draw किए जाते हैं',
    'tarot.process.2': 'हर card एक specific meaning और message देता है',
    'tarot.process.3': 'Reader intuition + symbolism से interpretation करता है',
    'tarot.best_for.title': 'किन questions के लिए best:',
    'tarot.best_for.1': 'Love & relationship',
    'tarot.best_for.2': 'Confusion / decision making',
    'tarot.best_for.3': 'किसी situation का outcome',
    'tarot.best_for.4': 'Emotional clarity',
    'tarot.best_for.5': 'Short-term future guidance',
    'tarot.cta.book': 'Book Tarot Reading',
    'tarot.cta.whatsapp': 'Talk on WhatsApp'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('hi');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'hi')) {
      setLanguageState(savedLang);
    }
    document.documentElement.lang = savedLang === 'en' ? 'en' : 'hi';
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === 'en' ? 'en' : 'hi';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    const translation = translations[language][key as keyof typeof translations['en']];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
